{% set version = "0.6.0" %}

package:
  name: jupyter-videochat
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter-videochat/jupyter-videochat-{{ version }}.tar.gz
  sha256: 8f555f1cf8a0f314964d54ad445fd2d303a2d9b9d17d8a4bcc870f3107ec94cd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - escapism
    - jupyterlab ==3.*
    - python >=3.7

test:
  imports:
    - jupyter_videochat
  commands:
    - pip check
    - jupyter labextension list
    - jupyter serverextension list
    - jupyter server extension list
  requires:
    - pip

about:
  home: https://github.com/jupyterlab-contrib/jupyter-videochat
  summary: Video Chat with peers inside JupyterLab and RetroLab
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - jupyter_videochat/labextension/static/third-party-licenses.json

extra:
  recipe-maintainers:
    - bollwyvl
