{% set version = "0.6.0" %}

package:
  name: jupyter-videochat
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyter-videochat/jupyter-videochat-{{ version }}.tar.gz
  sha256: 8f555f1cf8a0f314964d54ad445fd2d303a2d9b9d17d8a4bcc870f3107ec94cd

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - escapism
    - jupyterlab ==3.*
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - jupyter_videochat
  commands:
    - pip check
    - jupyter labextension list
    - jupyter serverextension list
    - jupyter server extension list

about:
  home: https://github.com/jupyterlab-contrib/jupyter-videochat
  summary: Video Chat with peers inside JupyterLab and RetroLab
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - jupyter_videochat/labextension/static/third-party-licenses.json

extra:
  recipe-maintainers:
    - bollwyvl
