{% set name = "jupyter-videochat" %}
{% set version = "0.5.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyter-videochat-{{ version }}.tar.gz
  sha256: c38cbc46e245fb53452226a4f6804f9e06171acd0fd1c60c5d3e751f7f881236

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - escapism
    - jupyterlab ==3.*
    - python >=3.6

test:
  imports:
    - jupyter_videochat
  commands:
    - pip check
    - jupyter labextension list
    - jupyter serverextension list
    - jupyter server extension list
  requires:
    - pip

about:
  home: https://github.com/yuvipanda/jupyter-videochat
  summary: Video Chat with peers inside JupyterLab
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
